context:
  version: "4.0.0-rc.1"

package:
  name: pueue
  version: ${{ version }}
  
source:
  url: https://github.com/Nukesor/pueue/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4005cdb038b0fe84cf25b46551920b14cedcbea265b6dac068b5ea4261ab4e2d

build:
  script: cargo install --locked --root ${{ PREFIX }} --path ./pueue --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}

tests:
  - script:
      - pueue --help