context:
  version: "0.13.0"

package:
  name: tui-journal
  version: ${{ version }}
  
source:
  url: https://github.com/AmmarAbouZor/tui-journal/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7f5e2b0b1b1a227cf9154c1f4749a0a645fc18a6cfa9750872b0b45400b1a0a6

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
  host:
    - if: linux
      then:
        - zlib
        - openssl
tests:
  - script:
      - tjournal --help