context:
  version: "1.7.1"

package:
  name: tealdeer
  version: ${{ version }}
  
source:
  url: https://github.com/tealdeer-rs/tealdeer/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2b10e141774d2a50d25a1d3ca3d911dedc0e1313366ce0a364068c7a686300d8

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}

tests:
  - script:
      - tldr --help