context:
  version: "0.3.3"

package:
  name: yazi
  version: ${{ version }}
  
source:
  url: https://github.com/sxyazi/yazi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fe2a458808334fe20eff1ab0145c78d684d8736c9715e4c51bce54038607dc4e

build:
  script: cargo install --locked --root ${{ PREFIX }} --path yazi-fm --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}

tests:
  - script:
      - yazi --help