context:
  version: "1.41.1"

package:
  name: cargo-insta
  version: ${{ version }}

source:
  url: https://github.com/mitsuhiko/insta/releases/download/${{ version }}/source.tar.gz
  sha256: 1228cd11eaad509adf1b9dc2fdd3ae5d3405cefdca3ecbd26102825244c76cb3

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - cargo-insta --help