context:
  version: "1.38.0"

package:
  name: cargo-insta
  version: ${{ version }}

source:
  url: https://github.com/mitsuhiko/insta/releases/download/${{ version }}/source.tar.gz
  sha256: 521d7a686a7cd0635f76930bebc49afb0b1da0e0fd54214e88d4e1ed11e17517

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - cargo-insta --help
