context:
  version: "0.14.1"

package:
  name: zenith
  version: ${{ version }}
  
source:
  url: https://github.com/bvaisvil/zenith/archive/refs/tags/${{ version }}.tar.gz
  sha256: 73d704b3cbf93506c22f3a7d98ae1a75011434a27a978dd0a7b6b30c7794423b

build:
  skip:
    - win
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - zenith --help