context:
  version: "1.16.1"

package:
  name: gping
  version: ${{ version }}
  
source:
  url: https://github.com/orf/gping/archive/refs/tags/gping-v${{ version }}.tar.gz
  sha256: 557dad6e54b5dd23f88224ea7914776b7636672f237d9cbbea59972235ca89a8

build:
  skip: win
  script:
    - if: unix
      then: 
        - cargo install --locked --root $PREFIX --path gping
        - rm $PREFIX/.crates.toml $PREFIX/.crates2.json
      else:
        - cargo install --locked --root %PREFIX% --path gping
        - rm %PREFIX%/.crates.toml %PREFIX%/.crates2.json

requirements:
  build:
    - ${{ compiler("rust") }}
  host:
    - ${{ "zlib" if linux }}

tests:
  - script:
      - gping --help
