context:
  version: "1.18.0"

package:
  name: gping
  version: ${{ version }}
  
source:
  url: https://github.com/orf/gping/archive/refs/tags/gping-v${{ version }}.tar.gz
  sha256: a76e09619831c0f2bb95f505a92c1332de89c3c43383b4d832a69afcb0fafd4c

build:
  skip: win
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
  host:
    - ${{ "zlib" if linux }}

tests:
  - script:
      - gping --help