context:
  version: "0.6.0"

package:
  name: daktilo
  version: ${{ version }}

source:
  url: https://github.com/orhun/daktilo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 594987ad0697a29e3d0dc25b220e5680cfaecedf2175fd6c17ba827fc7bc2978

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - if: linux
      then: pkg-config
  host:
    - if: linux
      then:
        - alsa-lib
        - xorg-libxi
        - xorg-libxtst

tests:
  - script:
      - daktilo --help