package:
  name: daktilo
  version: "0.5.0"

source:
  url: https://github.com/orhun/daktilo/archive/refs/tags/v0.5.0.tar.gz
  sha256: 55aead933dfe9176bc6f55f397bfe05f5eb97ef0f2b06e6904e4227f3e715b70

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - if: linux
      then: pkg-config
  host:
    - if: linux
      then:
        - alsa-lib
        - xorg-libxi
        - xorg-libxtst

tests:
  - script:
      - daktilo --help 
