package:
  name: cargo-sweep
  version: "0.7.0"

source:
  url: https://github.com/holmgr/cargo-sweep/archive/refs/tags/v0.7.0.tar.gz
  sha256: 21004272ffacbe19b5e2b6c521a021eb55abd24e96599fc5049c650abb708af2

build:
  script:
    - if: unix
      then:
        - cargo install --locked --root $PREFIX --path . --no-track
      else:
        - cargo install --locked --root %PREFIX% --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - cargo-sweep --help
