context:
  version: "0.7.0"

package:
  name: cargo-sweep
  version: ${{ version }}

source:
  url: https://github.com/holmgr/cargo-sweep/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 21004272ffacbe19b5e2b6c521a021eb55abd24e96599fc5049c650abb708af2

build:
  script: cargo install --locked --root ${{ PREFIX }} --path cargo-insta --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - cargo-sweep --help
