context:
  version: "0.1.13"

package:
  name: tokio-console
  version: ${{ version }}

source:
  url: https://github.com/tokio-rs/console/archive/refs/tags/tokio-console-v${{ version }}.tar.gz
  sha256: 562a45df9e4c2fafede3e265da7f96ba0f3f3891a3025be55ca064f2239a2203

build:
  script: cargo install --locked --root ${{ PREFIX }} --path tokio-console --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - tokio-console --help
