context:
  version: "0.1.9"

package:
  name: tokio-console
  version: ${{ version }}

source:
  url: https://github.com/tokio-rs/console/archive/refs/tags/tokio-console-v${{ version }}.tar.gz
  sha256: 4c54b486224d8ef97c113f2ffa3dc24ea6c5c7afe1784655fa5d3e9aa1242abb

build:
  script: cargo install --locked --root ${{ PREFIX }} --path tokio-console --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - tokio-console --help
