context:
  version: "2.2.0"

package:
  name: watchexec
  version: ${{ version }}
  
source:
  url: https://github.com/watchexec/watchexec/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 372def49d02a53864ede5fd821feb6f8de96bbbde8a94dbcd1b77aeed01d4a7b

build:
  script: cargo install --locked --root ${{ PREFIX }} --path ./crates/cli/ --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - watchexec --help