context:
  version: "1.1.5"

package:
  name: lsd
  version: ${{ version }}
  
source:
  url: https://github.com/lsd-rs/lsd/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 120935c7e98f9b64488fde39987154a6a5b2236cb65ae847917012adf5e122d1

build:
  script: cargo install --locked --root ${{ PREFIX }} --path . --no-track

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
  host:
    - libgit2
    - zlib

tests:
  - script:
      - lsd --help